export const worldRegions = [
  ["Europe","Balkans","Nordic"],
  ["Asia","Caucasus","Middle East"],
  ["Africa"],
  ["North America","Central America","Caribbean"],
  ["South America"],
  ["Oceania","Micronesia","Melanesia","Polynesia"],
  ["Antarctica"],
  ["Atlantic"],
  ["Indian Ocean"],
]

export const worldTableColumns = [
  "flag",
  "flagProprortion",
  "name", 
  "domain",
  "soverignTo",
  "region",
  "bollard",
  "snowPole",
  "telePole",
  "roadMarkings",
  "signChevron",
  "signSpeed",
  "signStop",
  "signYield",
  "signCrossing",
  "signRailway",
  "signRoads",
]
